"use client";
import { useEffect, useState } from "react";
import { ArrowRight, Check, ExternalLink, Flag, GitBranch, History, Link2, RefreshCw, Search, Send, TrendingUp } from "lucide-react";
import type { TopicDetail, TopicSummary } from "@/db/repository";
import type { Actor } from "@/domain";
import type { SourceItem } from "@/providers/contracts";
import { Kanshan } from "./kanshan";
import { Avatar } from "./avatar";
import { BusyButton, ErrorNotice, useOperation } from "./dialog";
import { dateLabel, label, request } from "./client";

export function HistoryPanel({ data, onRevision, onSource }: { data: TopicDetail; onRevision: (id: string) => void; onSource: (ids: string[]) => void }) {
  return <div>{data.revisions.length > 0 && <><h3 className="panel-section-title">看山提出的修订</h3><div className="revision-list">{data.revisions.map(r => <button className="revision-list-item" key={r.id} onClick={() => onRevision(r.id)}><span className="revision-icon"><GitBranch size={19} /></span><span><strong>{label(r.status)} · {r.proposedConditions.length} 个适用条件</strong><small>{r.explanation}</small><em>{dateLabel(r.createdAt)} · {r.modelRun.mode === "replay" ? "演示逻辑" : "模型建议"}</em></span><ArrowRight size={18} /></button>)}</div></>}
    <h3 className="panel-section-title">答案的每一次生长</h3><div className="version-timeline">{data.versions.map(v => <article key={v.id} className="version-entry"><span className="version-dot" /><div className="version-title"><strong>v{v.versionNumber}.0</strong><span className={`mode-tag ${v.status === "published" ? "live" : "replay"}`}>{label(v.status)}</span><time>{dateLabel(v.publishedAt)}</time></div><p>{v.text}</p><div className="version-conditions">{v.conditionsSnapshot.map((c, i) => <button key={c.id ?? i} onClick={() => onSource(c.evidenceIds)}><Link2 size={13} /> {c.label}</button>)}</div><div className="version-credit"><span>贡献：{v.contributorDisplaySnapshot.join("、") || "暂无贡献者记录"}</span><span>审阅：{v.reviewerDisplayName ?? "教学示例初始版本"}</span></div></article>)}</div>
  </div>;
}

export function ExperiencePanel({ experience, data, user, onUpdated, onClose, onReport, onSource, notify }: { experience: TopicDetail["experiences"][number]; data: TopicDetail; user: Actor | null; onUpdated: () => Promise<void>; onClose: () => void; onReport: () => void; onSource: (ids: string[]) => void; notify: (message: string) => void }) {
  const { busy, run, error } = useOperation("analyzing"); const [confirm, setConfirm] = useState(false);
  return <div><div className="public-preview"><div className="preview-byline"><Avatar name={experience.displayName} url={experience.displayAvatarUrl} /><strong>{experience.displayName}</strong><span>{dateLabel(experience.createdAt)}</span></div><p>{experience.publicText}</p></div>
    {experience.replyToProbeQuestion && <div className="reply-context"><span className="small-caption">回应的下一问</span><p>{experience.replyToProbeQuestion}</p></div>}{experience.sourceUrl && <div className="contribution-citation"><Link2 size={15} /><a href={experience.sourceUrl} target="_blank" rel="noreferrer">贡献者提供的原始来源 <ExternalLink size={14} /></a><small>尚需结合上下文核对</small></div>}
    <h3 className="panel-section-title"><Kanshan pose="working" alt="" /> 看山找到的关联</h3>{experience.matches.map(m => <article key={m.id} className="match-card"><div><span className={`status-chip ${m.relation === "support" ? "supported" : m.relation === "conflict" ? "contested" : "unknown"}`}>{label(m.relation)}</span><small>{m.modelRun.mode === "replay" ? "演示逻辑整理" : "模型整理"}</small></div><div className="match-conditions">{m.conditionIds.map(id => <span key={id}>{data.conditions.find(c => c.id === id)?.label ?? "相关条件已更新"}</span>)}</div><ol>{m.reasons.map((reason, i) => <li key={i}>{reason}</li>)}</ol><button className="text-button" onClick={() => onSource(m.evidenceIds)}><Link2 size={14} /> 查看关联依据</button></article>)}
    {!experience.matches.length && <div className="soft-callout"><Kanshan pose={experience.analysisStatus === "failed" ? "sleep" : "working"} /><p>{experience.analysisStatus === "processing" ? "看山正在认真整理，稍等一下。" : experience.status !== "active" ? "这份贡献已隐藏，相关关联不再展示。" : "暂时还没有可展示的关联。经历已保存，可以请看山再整理一次。"}</p></div>}
    {experience.caveats.length > 0 && <div className="caveat-list"><strong>还需要保留的疑问</strong><ul>{experience.caveats.map((c, i) => <li key={i}>{c}</li>)}</ul></div>}
    <ErrorNotice message={error ?? experience.analysisError ?? null} />{experience.status === "active" && (experience.isOwner || user?.role === "maintainer") && <BusyButton busy={busy} className="secondary-button" onClick={() => run(async () => { await request(`experiences/${experience.id}/reanalyze`, {}); await onUpdated(); notify("已检查整理状态，结果会在这里更新。"); })}><RefreshCw size={15} /> {experience.analysisStatus === "processing" ? "检查整理状态" : "请看山再整理一次"}</BusyButton>}
    {experience.isOwner ? <details className="review-alternatives"><summary>管理这份贡献</summary><p className="field-hint">撤回后不再公开展示；删除还会清理这份经历保存的原始正文。引用它的历史版本会显示来源不可用。</p><label className="check-field"><input type="checkbox" checked={confirm} onChange={e => setConfirm(e.target.checked)} /><span>我确认处理这份经历。</span></label><div className="button-row"><BusyButton busy={busy} className="secondary-button" disabled={!confirm || experience.status !== "active"} onClick={() => run(async () => { await request(`experiences/${experience.id}/withdraw`, { confirmed: true }); await onUpdated(); notify("这份经历已撤回，相关公开内容已隐藏。"); onClose(); })}>撤回公开展示</BusyButton><BusyButton busy={busy} className="text-button danger-text" disabled={!confirm || experience.status === "deleted"} onClick={() => run(async () => { await request(`experiences/${experience.id}`, { confirmed: true }, "DELETE"); await onUpdated(); notify("经历正文已删除，保留最小操作记录。"); onClose(); })}>删除经历正文</BusyButton></div></details> : user && <button className="text-button report-link" onClick={onReport}><Flag size={14} /> 反馈这份内容的问题</button>}
  </div>;
}

export function ReportPanel({ entityType, entityId, onDone }: { entityType: string; entityId: string; onDone: () => void }) {
  const [reason, setReason] = useState(""); const { busy, run, error } = useOperation(); const [saved, setSaved] = useState(false);
  if (saved) return <div className="success-flow"><Kanshan pose="idle" /><h3>谢谢你帮忙看仔细。</h3><p>反馈已交给维护者，相关内容将在审核流程中核对。</p><button className="primary-button" onClick={onDone}>回到议题</button></div>;
  return <form onSubmit={e => { e.preventDefault(); run(async () => { await request("reports", { entityType, entityId, reason }); setSaved(true); }); }}><p className="flow-description">指出具体问题，可以帮助维护者更快核对。请不要在反馈中填写他人的隐私信息。</p><label className="field"><span>你发现了什么问题？</span><textarea autoFocus data-autofocus="true" value={reason} onChange={e => setReason(e.target.value)} rows={5} required minLength={5} maxLength={1000} placeholder="例如：这段引用遗漏了重要的适用条件……" /></label><ErrorNotice message={error} /><BusyButton busy={busy} type="submit"><Flag size={16} /> 提交内容反馈</BusyButton></form>;
}

export function DiscussionPanel({ data, user, onUpdated, onExperience, onClose, onReply, onContribution, notify }: { data: TopicDetail; user: Actor | null; onUpdated: () => Promise<void>; onExperience: () => void; onClose: () => void; onReply: (probeId: string) => void; onContribution: (experienceId: string) => void; notify: (message: string) => void }) {
  const { busy, run, error } = useOperation();
  return <div><div className="flow-intro"><Send size={19} /><p>每条下一问都经过确认。送达状态和回执会保存在这里，方便继续邀请、收集和追问。</p></div><ErrorNotice message={error} />{data.publications.length ? <div className="publication-list">{data.publications.map(p => <article key={p.id} className="publication-card"><div className="publication-top"><strong>{p.target === "in_app" ? "议题讨论区" : `知乎圈子 · ${p.targetCircleId}`}</strong><span className={`mode-tag ${p.providerMode}`}>{p.providerMode === "replay" ? "演示" : "真实"} · {label(p.status)}</span></div><p>{p.text}</p><div className="publication-meta"><span>{p.displayIdentity} · {dateLabel(p.sentAt ?? p.createdAt)}</span>{p.remoteUrl && <a href={p.remoteUrl} target="_blank" rel="noreferrer">查看知乎回执 <ExternalLink size={14} /></a>}</div>{p.lastError && <p className="inline-warning">{p.lastError}</p>}{["pending", "retryable_failed"].includes(p.status) && p.nextAttemptAt && <p className="field-hint">下次可尝试时间：{dateLabel(p.nextAttemptAt)}{p.status === "retryable_failed" ? " · 由维护者确认重试" : " · 队列将按额度继续发送"}</p>}{p.status === "needs_reconciliation" && <p className="inline-warning">送达结果尚不确定，请维护者先到目标位置核对，避免重复发送。</p>}{p.status === "retryable_failed" && user?.role === "maintainer" && <BusyButton busy={busy} className="secondary-button" onClick={() => run(async () => { await request(`publications/${p.id}/retry`, { confirmed: true }); await onUpdated(); notify("已重新加入发送队列。"); })}><RefreshCw size={15} /> 确认重试发送</BusyButton>}{p.status === "sent" && !p.hasUnavailableEvidence && <button className="secondary-button reply-button" onClick={() => onReply(p.probeId)}><ArrowRight size={15} /> 回答这条下一问</button>}<div className="discussion-replies">{data.experiences.filter(e => e.replyToProbeId === p.probeId && e.status === "active").map(e => <button className="discussion-reply" key={e.id} onClick={() => onContribution(e.id)}><span><strong>{e.displayName}</strong><small>{dateLabel(e.createdAt)}</small></span><p>{e.publicText}</p><em>查看回复与依据 <ArrowRight size={13} /></em></button>)}</div></article>)}</div> : <div className="empty-panel"><Kanshan pose="sleep" /><p>还没有发出的下一问。<br />先看看看山的小问题，确认后再邀请大家。</p></div>}
    <div className="dialog-actions"><button className="primary-button" onClick={onExperience}>我有一段相关经历 <ArrowRight size={16} /></button></div><button className="text-button" onClick={onClose}>回到当前答案</button>
  </div>;
}

type CandidateResult = { candidates: (SourceItem & { candidateId: string })[]; dataStatus: { mode: "live" | "replay"; fetchedAt: string }; filteredCount: number };
type CandidateAttempt = { query: string | null; startedAt: string; status: "loading" | "failed"; error?: string };
const candidateQueryLabel = (query: string | null) => query === null ? "当前热点" : `“${query}”`;
function candidateSourceUrl(value?: string) {
  if (!value) return null;
  try { const url = new URL(value); return ["https:", "http:"].includes(url.protocol) ? url.href : null; } catch { return null; }
}

export function NewTopicPanel({ user, onCreated }: { user: Actor; onCreated: (topic: TopicSummary) => Promise<void> }) {
  const [query, setQuery] = useState(""); const [result, setResult] = useState<(CandidateResult & { query: string | null }) | null>(null); const [attempt, setAttempt] = useState<CandidateAttempt | null>(null); const [selected, setSelected] = useState<string[]>([]); const [title, setTitle] = useState(""); const [template, setTemplate] = useState<"learning" | "social">("social"); const { busy, run, error } = useOperation();
  const loadCandidates = (search?: string) => run(async () => {
    const nextAttempt: CandidateAttempt = { query: search ?? null, startedAt: new Date().toISOString(), status: "loading" };
    setAttempt(nextAttempt);
    try {
      const r = await request<CandidateResult>(search === undefined ? "topics/candidates" : `topics/candidates?query=${encodeURIComponent(search)}`);
      setResult({ ...r, query: nextAttempt.query }); setSelected([]); setAttempt(null);
    } catch (e) {
      setAttempt({ ...nextAttempt, status: "failed", error: e instanceof Error ? e.message : "连接暂时中断，请稍后重试。" });
    }
  }, "searching");
  const candidateMode = result?.dataStatus.mode ?? user.mode;
  return <div><p className="flow-description">从一个值得继续讨论的问题开始。可以先看看知乎里的线索，再决定议题怎么问。</p><form className="candidate-search" onSubmit={e => { e.preventDefault(); void loadCandidates(query.trim()); }}><label className="field"><span>寻找议题线索</span><input value={query} onChange={e => setQuery(e.target.value)} required placeholder="例如：大学课程怎样使用 AI" maxLength={200} /></label><BusyButton busy={busy} type="submit" className="secondary-button" disabled={!query.trim()}><Search size={16} aria-hidden="true" /> 搜索</BusyButton><BusyButton busy={busy} type="button" className="secondary-button" onClick={() => void loadCandidates()}><TrendingUp size={16} aria-hidden="true" /> 看看当前热点</BusyButton></form>
    <section className="candidate-results" aria-label="议题候选">
      {attempt?.status === "failed" && <div className="candidate-recovery"><ErrorNotice message={`查询${candidateQueryLabel(attempt.query)}未完成：${attempt.error}`} /><p className="field-hint">本次尝试：<time dateTime={attempt.startedAt}>{dateLabel(attempt.startedAt)}</time>。{result ? "已保留上次结果、已选线索和议题草稿。" : "还没有可展示的查询结果，议题草稿已保留。"}</p><BusyButton busy={busy} className="secondary-button" onClick={() => void loadCandidates(attempt.query ?? undefined)}><RefreshCw size={15} aria-hidden="true" /> 重试这次查询</BusyButton></div>}
      <div className="candidate-result-status" role="status">
        {attempt?.status === "loading" && <p className="field-hint">正在查询{candidateQueryLabel(attempt.query)}……{result && "下方暂时保留上次结果。"}</p>}
        {result && <><div className="candidate-result-meta"><span className={`mode-tag ${candidateMode}`}>{candidateMode === "replay" ? "演示候选" : "真实知乎来源"}</span><span>{attempt ? "上次成功查询" : "查询"}：{candidateQueryLabel(result.query)}</span><span>{result.candidates.length} 条可选线索</span><span>抓取于 <time dateTime={result.dataStatus.fetchedAt}>{dateLabel(result.dataStatus.fetchedAt)}</time></span></div>{result.filteredCount > 0 && <p className="field-hint">有 {result.filteredCount} 条线索未通过展示检查，已过滤。</p>}</>}
        {result && candidateMode === "replay" && <p className="field-hint">当前显示演示候选，不代表真实知乎热度或用户观点。</p>}
      </div>
      {result?.candidates.length ? <div className="candidate-list">{result.candidates.map(c => {
        const sourceUrl = candidateSourceUrl(c.url);
        return <article key={c.candidateId} className="candidate-card"><label className="candidate-choice"><input type="checkbox" checked={selected.includes(c.candidateId)} onChange={e => { setSelected(prev => e.target.checked ? [...prev, c.candidateId] : prev.filter(id => id !== c.candidateId)); if (!title && c.title) setTitle(c.title); }} /><span><strong>{c.title ?? "一条讨论线索"}</strong><small>{c.summary}</small></span></label><div className="candidate-source">{sourceUrl ? <a href={sourceUrl} target="_blank" rel="noreferrer" aria-label={`打开来源：${c.title ?? "一条讨论线索"}（新窗口）`}><ExternalLink size={14} aria-hidden="true" /><span>{sourceUrl}</span></a> : <span>{c.provenance.mode === "replay" ? "演示素材，无外部来源链接" : "来源未提供可打开的链接"}</span>}<span>抓取于 <time dateTime={c.provenance.fetchedAt}>{dateLabel(c.provenance.fetchedAt)}</time></span></div></article>;
      })}</div> : !attempt && <div className="soft-callout candidate-empty"><Kanshan pose="working" alt="" /><div><strong>{result ? "这次没有找到可用的议题线索" : "先找找值得追问的线索"}</strong><p>{result ? result.filteredCount > 0 ? "返回的线索都未通过展示检查。换个更具体的关键词，或看看当前热点，再选一个值得讨论的问题。" : "试试更具体的关键词，或看看当前热点。找到线索后，就可以选择来源创建议题。" : "输入关键词搜索，或看看当前热点，再选择来源创建议题。"}</p></div></div>}
    </section>
    <form onSubmit={e => { e.preventDefault(); run(async () => { const r = await request<{ topic: TopicSummary }>("topics", { title, template, sourceEvidenceIds: selected }); await onCreated(r.topic); }); }}><label className="field"><span>我们想一起讨论的问题</span><textarea value={title} onChange={e => setTitle(e.target.value)} required minLength={5} maxLength={200} rows={2} placeholder="写一个具体、开放、值得继续追问的问题" /></label><label className="field"><span>议题类型</span><select value={template} onChange={e => setTemplate(e.target.value as typeof template)}><option value="social">社会观察</option><option value="learning">学习与成长</option></select></label><ErrorNotice message={error} /><BusyButton busy={busy} type="submit" disabled={!selected.length}><Check size={17} /> 确认创建这个议题</BusyButton></form>
  </div>;
}

type Report = { id: string; entityType: string; entityId: string; reason: string; status: string; createdAt: string };
type AuditEntry = { id: string; type: string; occurredAt: string; payloadSummary: Record<string, unknown> };
export function ReviewLogPanel({ topicId, mode, onUpdated }: { topicId: string; mode: "reports" | "audit"; onUpdated: () => Promise<void> }) {
  const [reports, setReports] = useState<Report[]>([]); const [audit, setAudit] = useState<AuditEntry[]>([]); const [reasons, setReasons] = useState<Record<string, string>>({}); const [loading, setLoading] = useState(true); const { busy, run, error } = useOperation();
  const load = async () => { if (mode === "reports") setReports(await request<Report[]>(`topics/${topicId}/reports`)); else setAudit(await request<AuditEntry[]>(`topics/${topicId}/audit`)); setLoading(false); };
  useEffect(() => { void run(load); /* Current panel owns this bounded read. */ }, [topicId, mode]);
  return <div><ErrorNotice message={error} />{loading && !error && <p className="field-hint">正在打开小本子……</p>}{error && <BusyButton busy={busy} className="secondary-button" onClick={() => run(load)}>重新读取</BusyButton>}{mode === "reports" ? reports.length ? reports.map(r => <article key={r.id} className="report-card"><div className="publication-top"><strong>内容反馈</strong><span className="mode-tag">{r.status === "pending" ? "待处理" : r.status === "hidden" ? "已隐藏" : "已保留"}</span></div><p>{r.reason}</p><span className="field-hint">{dateLabel(r.createdAt)} · {r.entityType}</span>{r.status === "pending" && <><label className="field"><span>处理说明（至少 5 字）</span><input value={reasons[r.id] ?? ""} onChange={e => setReasons(prev => ({ ...prev, [r.id]: e.target.value }))} minLength={5} maxLength={1000} /></label><div className="button-row">{(["dismiss", "hide"] as const).map(decision => <BusyButton key={decision} busy={busy} disabled={(reasons[r.id] ?? "").trim().length < 5} className="secondary-button" onClick={() => run(async () => { await request(`reports/${r.id}/decision`, { decision, reason: reasons[r.id] }); await load(); await onUpdated(); })}>{decision === "hide" ? "隐藏相关内容" : "保留内容，结束审核"}</BusyButton>)}</div></>}</article>) : !loading && <div className="empty-panel"><Kanshan pose="idle" /><p>当前没有待处理的内容反馈。</p></div> : <div className="audit-list">{audit.map(a => <div className="audit-row" key={a.id}><History size={16} /><div><strong>{auditLabel(a.type)}</strong><small>{dateLabel(a.occurredAt)}</small>{Boolean(a.payloadSummary.versionNumber) && <span>v{String(a.payloadSummary.versionNumber)}.0</span>}</div></div>)}</div>}</div>;
}
const auditNames: Record<string, string> = { "topic.seeded": "教学议题已准备", "topic.created": "创建议题", "source.refreshed": "更新来源", "experience.submitted": "收到一份经历", "experience.analyzed": "看山整理了经历", "experience.withdrawn": "贡献者撤回了经历", "experience.deleted": "贡献者删除了经历", "probe.proposed": "看山提出下一问", "probe.approved": "维护者确认下一问", "probe.reviewed": "维护者审阅下一问", "publication.requested": "下一问加入发送队列", "publication.sent": "下一问已送达", "revision.proposed": "看山提出答案修订", "revision.accepted": "答案更新为新版本", "revision.reviewed": "维护者审阅修订", "report.created": "收到内容反馈", "report.resolved": "内容反馈已处理" };
function auditLabel(value: string) { return auditNames[value] ?? "记录了一次流程变化"; }
