"use client";
import { useState } from "react";
import { ArrowRight, Check, CheckCircle2, ExternalLink, Feather, GitBranch, Link2, LockKeyhole, RefreshCw, Flag, ShieldCheck, Sparkles } from "lucide-react";
import type { TopicDetail } from "@/db/repository";
import type { Actor, DisplayMode, Redaction } from "@/domain";
import { Kanshan } from "./kanshan";
import { Avatar } from "./avatar";
import { BusyButton, ErrorNotice, useOperation } from "./dialog";
import { dateLabel, label, request, type Session, type Theme, themes } from "./client";
import { browserDemo } from "./runtime";

type FlowProps = { data: TopicDetail; user: Actor; onUpdated: () => Promise<void>; onClose: () => void; notify: (message: string) => void };
export type ContributionKind = "experience" | "comment" | "evidence";
type Preview = { publicText: string; redactions: Redaction[]; displayIdentity: string; displayAvatarUrl?: string | null; previewHash: string; expiresAt: string; contributionKind: ContributionKind; replyToProbeId?: string | null; replyToProbeQuestion?: string | null; sourceUrl?: string | null };
function IdentityFields({ mode, setMode, pseudonym, setPseudonym, nickname }: { mode: DisplayMode; setMode: (mode: DisplayMode) => void; pseudonym: string; setPseudonym: (name: string) => void; nickname: string }) {
  return <fieldset className="identity-field"><legend>这次用什么名字分享？</legend><div className="segmented">{([["nickname", "昵称"], ["anonymous", "匿名"], ["pseudonym", "化名"]] as const).map(([value, name]) => <label key={value}><input type="radio" name="displayMode" value={value} checked={mode === value} onChange={() => setMode(value)} /><span>{name}</span></label>)}</div>{mode === "pseudonym" ? <label className="field"><span>这次使用的化名</span><input value={pseudonym} onChange={e => setPseudonym(e.target.value)} minLength={2} maxLength={24} placeholder="2–24 字，例如：一颗小石头" required /></label> : <p className="field-hint">对外显示：{mode === "anonymous" ? "匿名知友" : nickname}</p>}</fieldset>;
}

export function LoginFlow({ session, onLoggedIn }: { session: Session | null; onLoggedIn: () => Promise<void> }) {
  const { run, busy, error } = useOperation();
  return <div className="login-flow"><Kanshan pose="wave" /><h3>嘿，就差你的那一块拼图。</h3><p>登录后，记录自己的经历。看山会整理其中的条件，把每一份贡献留在它该在的位置。</p><ErrorNotice message={error} />
    {session?.capabilities.zhihuOAuth.available ? <a className="primary-button" href="/api/auth/zhihu/start?returnTo=%2F"><LockKeyhole size={17} /> 使用知乎账号登录 <ArrowRight size={17} /></a> : <div className="soft-callout"><LockKeyhole size={18} /><div><strong>{browserDemo ? "在线演示，无需知乎登录" : "知乎登录尚未配置完成"}</strong><p>{browserDemo ? "选择下方身份开始体验。使用虚构资料即可，记录仅保存在当前浏览器。" : "维护者接入官方授权后，这里即可使用真实账号。现在可以先体验完整流程。"}</p></div></div>}
    {session?.capabilities.demo && <div className="demo-options"><span className="small-caption">独立体验空间 · 使用教学素材与演示逻辑</span><BusyButton busy={busy} onClick={() => run(async () => { await request("auth/demo", { role: "maintainer" }); await onLoggedIn(); })}><Sparkles size={17} /> 和看山体验完整流程</BusyButton><BusyButton busy={busy} className="secondary-button" onClick={() => run(async () => { await request("auth/demo", { role: "contributor" }); await onLoggedIn(); })}>以经验贡献者身份体验</BusyButton><p className="field-hint">每次创建独立空间。体验内容不会发送到知乎。</p></div>}
  </div>;
}

export function ExperienceFlow({ data, user, onUpdated, onClose, notify, initialKind = "experience", replyToProbeId }: FlowProps & { initialKind?: ContributionKind; replyToProbeId?: string }) {
  const [contributionKind, setContributionKind] = useState<ContributionKind>(initialKind); const [sourceUrl, setSourceUrl] = useState("");
  const replyTo = data.probes.find(p => p.id === replyToProbeId);
  const minimumLength = contributionKind === "experience" ? 20 : contributionKind === "comment" ? 5 : 10;
  const kindLabel = contributionKind === "experience" ? "亲身经历" : contributionKind === "comment" ? "评论与回复" : "补充来源";
  const [text, setText] = useState(""); const [mode, setMode] = useState<DisplayMode>("nickname"); const [pseudonym, setPseudonym] = useState(""); const [preview, setPreview] = useState<Preview | null>(null); const [confirmed, setConfirmed] = useState(false); const [saved, setSaved] = useState(false);
  const { run, busy, error, setError } = useOperation();
  const identity = { displayMode: mode, ...(mode === "pseudonym" ? { pseudonym } : {}), contributionKind, ...(replyToProbeId ? { replyToProbeId } : {}), ...(contributionKind === "evidence" ? { sourceUrl } : {}) };
  const edit = () => { setPreview(null); setConfirmed(false); setError(null); };
  if (saved) return <div className="success-flow"><Kanshan pose="play" /><CheckCircle2 size={29} /><h3>{contributionKind === "experience" ? "你的经历，已经收好了。" : contributionKind === "comment" ? "你的回复，已经收好了。" : "这份来源，已经收好了。"}</h3><p>看山的整理结果会显示在经验卡片里。新的经历会先补充证据，再由维护者决定是否修订公共答案。</p><button className="primary-button" onClick={onClose}>看看我的经历 <ArrowRight size={17} /></button></div>;
  return <form onSubmit={e => { e.preventDefault(); run(async () => {
    if (!preview) { setPreview(await request<Preview>(`topics/${data.topic.id}/experiences/preview`, { text, ...identity })); return; }
    const result = await request<{ analysisStatus: string }>(`topics/${data.topic.id}/experiences`, { text, publicText: preview.publicText, ...identity, previewHash: preview.previewHash, confirmed: true });
    await onUpdated(); setSaved(true); notify(result.analysisStatus === "failed" ? "经历已保存；看山暂时没能完成整理，可以稍后重试。" : "经历已保存。看看它带来的新条件吧。");
  }, preview ? "analyzing" : undefined); }}>
    {!preview ? <><fieldset className="identity-field"><legend>这次想补充什么？</legend><div className="segmented">{([["experience", "亲身经历"], ["comment", "评论与回复"], ["evidence", "补充来源"]] as const).map(([value, title]) => <label key={value}><input type="radio" name="contributionKind" value={value} checked={contributionKind === value} onChange={() => setContributionKind(value)} /><span>{title}</span></label>)}</div></fieldset>{replyToProbeId && <div className="reply-context"><span className="small-caption">正在回答这条下一问</span><p>{replyTo?.question ?? "这条问题的内容暂不可用，请关闭后重新选择。"}</p></div>}<div className="flow-intro"><Feather size={19} /><p>{contributionKind === "experience" ? "讲一件你亲身遇到的事：当时想做什么，遇到了什么，后来怎么样了。具体的过程比结论更有帮助。" : contributionKind === "comment" ? "回应一个具体问题，补充不同的条件或疑问。看山会保留它回应的问题，并整理可以核对的部分。" : "附上一份原始来源，说明它支持或质疑哪个条件。你提供的链接会标注为待核对的贡献。"}</p></div><label className="field"><span>{contributionKind === "experience" ? "我的经历" : contributionKind === "comment" ? "我的评论或回复" : "这份来源说明了什么"}</span><textarea autoFocus data-autofocus="true" value={text} onChange={e => setText(e.target.value)} placeholder="例如：我没有编程经验，用 AI 做出了第一版……但上线后……" minLength={minimumLength} maxLength={6000} rows={7} required /><span className="field-hint">至少 {minimumLength} 字 · {text.length} / 6000</span></label>
      {contributionKind === "evidence" && <label className="field"><span>原始来源链接</span><input type="url" value={sourceUrl} onChange={e => setSourceUrl(e.target.value)} required placeholder="https://…" maxLength={2000} /><small className="field-hint">填写可公开访问的 HTTPS 页面。系统会保存你的引用，不代表已验证页面内容。</small></label>}
      {user.mode === "replay" && contributionKind === "experience" && <button className="text-button" type="button" onClick={() => setText("我没有编程经验，用 AI 做了一个给社团报名的小工具。上线第一周有十几个人使用，但表单重复提交后，数据出现了错误。我先备份数据，再让 AI 解释原因，最后通过重复提交测试确认修复有效。现在每周仍要检查日志，维护的时间比最初想象的多。")}>填入一段演示经历</button>}
      <IdentityFields mode={mode} setMode={setMode} pseudonym={pseudonym} setPseudonym={setPseudonym} nickname={user.displayName} /><div className="soft-callout"><ShieldCheck size={19} /><p>下一步检查公开预览。系统会尝试隐藏常见手机号、邮箱和身份证号，也请你自行检查其他隐私信息。</p></div></> : <>
      <div className="step-indicator"><span className="done"><Check size={14} /> 写下经历</span><span>2 · 检查公开内容</span></div><div className="public-preview"><div className="preview-byline"><Avatar name={preview.displayIdentity} url={preview.displayAvatarUrl} /><strong>{preview.displayIdentity}</strong><span>{kindLabel} · 将公开展示</span></div>{replyToProbeId && <p className="field-hint">回应：{preview.replyToProbeQuestion ?? "来源暂不可用"}</p>}<p>{preview.publicText}</p>{preview.sourceUrl && <a className="contribution-source" href={preview.sourceUrl} target="_blank" rel="noreferrer">所附原始来源 <ExternalLink size={14} /></a>}</div><p className="field-hint">{preview.redactions.length ? `已隐藏 ${preview.redactions.length} 处常见隐私信息。` : "未检测到常见手机号、邮箱或身份证号。"}请仔细检查这份公开预览。</p><label className="check-field"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} required /><span>我确认公开以上内容与身份，并交给看山整理。</span></label><button type="button" className="text-button" onClick={edit}>返回修改</button>
    </>}
    <ErrorNotice message={error} /><div className="dialog-actions"><BusyButton busy={busy} type="submit" disabled={!!preview && !confirmed}>{preview ? contributionKind === "experience" ? "确认贡献这份经历" : contributionKind === "comment" ? "确认提交这条回复" : "确认补充这份来源" : "检查公开预览"}<ArrowRight size={17} /></BusyButton></div>
  </form>;
}

type ProbePreview = { text: string; target: "in_app"; displayIdentity: string; sourceUrls: string[]; baseVersionId: string; previewHash: string; expiresAt: string; providerMode: string; title?: string };
export function ProbeFlow({ data, user, probe, onUpdated, onClose, notify }: FlowProps & { probe: TopicDetail["probes"][number] }) {
  const [question, setQuestion] = useState(probe.question); const [mode, setMode] = useState<DisplayMode>("nickname"); const [pseudonym, setPseudonym] = useState(""); const [preview, setPreview] = useState<ProbePreview | null>(null); const [confirmed, setConfirmed] = useState(false); const [reason, setReason] = useState("");
  const { run, busy, error } = useOperation("asking"); const canReview = ["draft", "needs_review", "deferred"].includes(probe.status) && user.role === "maintainer" && !probe.hasUnavailableEvidence;
  const unknown = data.conditions.find(c => c.id === probe.targetUnknownId);
  const body = { question, target: "in_app" as const, displayMode: mode, ...(mode === "pseudonym" ? { pseudonym } : {}) };
  async function decide(decision: "defer" | "reject") { await request(`probes/${probe.id}/decision`, { decision, reason }); await onUpdated(); notify(decision === "defer" ? "先收进小本子，稍后再看。" : "这条下一问未采纳，已有答案保持原样。"); onClose(); }
  return <form onSubmit={e => { e.preventDefault(); run(async () => { if (!preview) { setPreview(await request<ProbePreview>(`probes/${probe.id}/preview`, body)); return; } await request(`probes/${probe.id}/approve`, { ...body, confirmed: true, previewHash: preview.previewHash }); await onUpdated(); notify("已确认，正在排队发送。送达后会显示回执。"); onClose(); }); }}>
    <div className="soft-callout"><Sparkles size={19} /><div><strong>为什么想问这个</strong><p>{probe.rationale}</p><p>{probe.informationGainExplanation}</p></div></div>
    <div className="probe-context"><span className="small-caption">这次想弄明白</span><strong>{unknown?.label ?? "原来的待验证条件已更新"}</strong>{unknown?.description && <p>{unknown.description}</p>}<details><summary>查看依据与整理记录</summary><div className="diff-sources">{probe.evidenceIds.map(id => { const evidence = data.evidence.find(e => e.id === id); return evidence ? <article key={id}><strong>{evidence.displayAuthor}</strong><p>{evidence.summary}</p>{evidence.url && <a href={evidence.url} target="_blank" rel="noreferrer">查看原始来源 <ExternalLink size={13} /></a>}</article> : <p key={id}>来源暂不可用</p>; })}</div><p className="field-hint">{probe.modelRun.mode === "replay" ? "本地演示逻辑" : "模型"}：{probe.modelRun.model}<br />提示版本：{probe.modelRun.promptVersion} · 规则版本：{probe.modelRun.rulesVersion}<br />整理时间：{dateLabel(probe.modelRun.createdAt)}</p></details></div>
    {preview ? <><div className="public-preview"><span className="small-caption">本站议题讨论区 · {preview.providerMode === "replay" ? "演示空间" : "公开展示"}</span>{preview.title && <h3>{preview.title}</h3>}<p>{preview.text}</p></div><p className="field-hint">公开身份：{preview.displayIdentity} · 预览有效至 {dateLabel(preview.expiresAt)}</p><label className="check-field"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} required /><span>我已检查正文、身份、来源与目标，确认发出这条下一问。</span></label><button type="button" className="text-button" onClick={() => { setPreview(null); setConfirmed(false); }}>返回修改</button></> : <>
      <label className="field"><span>下一问正文</span><textarea autoFocus data-autofocus="true" value={question} onChange={e => setQuestion(e.target.value)} rows={4} minLength={10} maxLength={3000} required readOnly={!canReview} /></label>
      {canReview && <><p className="field-hint">确认后，这条下一问会出现在本站议题讨论区，大家可以在这里回复。</p><IdentityFields mode={mode} setMode={setMode} pseudonym={pseudonym} setPseudonym={setPseudonym} nickname={user.displayName} /></>}
    </>}
    <ErrorNotice message={error} />{canReview ? <><div className="dialog-actions"><BusyButton busy={busy} type="submit" disabled={!!preview && !confirmed}>{preview ? "确认发出这条下一问" : "预览后再决定"}<ArrowRight size={17} /></BusyButton></div>{!preview && <details className="review-alternatives"><summary>暂时不发出这条问题</summary><label className="field"><span>留个理由（选填）</span><input value={reason} onChange={e => setReason(e.target.value)} maxLength={1000} /></label><div className="button-row"><BusyButton type="button" busy={busy} className="secondary-button" onClick={() => run(() => decide("defer"))}>稍后再看</BusyButton><BusyButton type="button" busy={busy} className="text-button danger-text" onClick={() => run(() => decide("reject"))}>不采纳这条</BusyButton></div></details>}</> : <p className="field-hint">当前状态：{label(probe.status)}。{user.role !== "maintainer" && "由维护者决定是否发出。"}</p>}
  </form>;
}

export function RevisionFlow({ data, user, revision, onUpdated, onClose, notify }: Omit<FlowProps, "user"> & { user: Actor | null; revision: TopicDetail["revisions"][number] }) {
  const [confirmed, setConfirmed] = useState(false); const [reason, setReason] = useState(""); const { run, busy, error } = useOperation("updating");
  const canReview = user?.role === "maintainer" && ["proposed", "needs_review", "deferred"].includes(revision.status); const current = revision.baseVersionId === data.topic.currentVersionId;
  async function decide(decision: "accept" | "reject" | "defer") { await request(`revisions/${revision.id}/decision`, { decision, baseVersionId: revision.baseVersionId, reason, ...(decision === "accept" ? { confirmed: true } : {}) }); await onUpdated(); notify(decision === "accept" ? "答案长出了新版本，旧版本也好好保存着。" : decision === "reject" ? "这份修订未采纳，当前答案未改变。" : "修订已暂缓，当前答案未改变。"); onClose(); }
  return <div><div className="soft-callout"><GitBranch size={20} /><div><strong>看山这次发现了什么</strong><p>{revision.explanation}</p><span className="small-caption">{revision.modelRun.mode === "replay" ? "本地演示逻辑" : `模型：${revision.modelRun.model}`} · {label(revision.status)}</span></div></div><div className="diff-list">{revision.diff.map((diff, i) => <article key={i} className={`diff-card diff-${diff.kind}`}><div className="diff-label">{diff.kind === "added" ? "新增" : diff.kind === "removed" ? "移除" : "修改"}<span>{diff.reason}</span></div>{diff.before && <div className="diff-before"><span>原来</span><p>{diff.before}</p></div>}{diff.after && <div className="diff-after"><span>建议改为</span><p>{diff.after}</p></div>}<div className="diff-sources">{diff.evidenceIds.map(id => { const e = data.evidence.find(e => e.id === id); return e ? <details key={id}><summary><Link2 size={13} /> {e.displayAuthor}</summary><p>{e.summary}</p>{e.url && <a href={e.url} target="_blank" rel="noreferrer">查看原始来源 <ExternalLink size={13} /></a>}</details> : <span key={id}>来源暂不可用</span>; })}</div></article>)}</div>
    <details className="full-version"><summary>查看建议的新版本全文</summary><p>{revision.proposedText}</p></details>
    {canReview && <><ErrorNotice message={!current ? "公共答案已有更新。这份建议基于旧版本，请重新生成修订。" : error} /><label className="check-field"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} /><span>我已核对变化与依据，同意将它更新为公共答案的新版本。</span></label><label className="field"><span>审阅备注（选填）</span><textarea rows={2} value={reason} onChange={e => setReason(e.target.value)} maxLength={1000} /></label><div className="dialog-actions"><BusyButton busy={busy} disabled={!confirmed || !current || revision.status === "needs_review" || revision.hasUnavailableEvidence} onClick={() => run(() => decide("accept"))}><Check size={17} /> 采纳并发布新版本</BusyButton><div className="button-row"><BusyButton busy={busy} className="secondary-button" onClick={() => run(() => decide("defer"))}>稍后再看</BusyButton><BusyButton busy={busy} className="text-button danger-text" onClick={() => run(() => decide("reject"))}>不采纳这份修订</BusyButton></div></div></>}
  </div>;
}

export function SourcesFlow({ data, user, onUpdated, notify, focusIds, onReport, onContributeSource }: { data: TopicDetail; user: Actor | null; onUpdated: () => Promise<void>; notify: (message: string) => void; focusIds?: string[]; onReport?: (id: string) => void; onContributeSource?: () => void }) {
  const { run, busy, error } = useOperation("searching"); const [selected, setSelected] = useState<string[]>([]); const [query, setQuery] = useState(data.topic.title); const [onlyFocused, setOnlyFocused] = useState(!!focusIds?.length);
  return <div>{user?.role === "maintainer" && <div className="source-tools"><label className="field"><span>从知乎寻找更多经验</span><input value={query} maxLength={200} onChange={e => setQuery(e.target.value)} /></label><div className="button-row"><BusyButton busy={busy} className="secondary-button" disabled={!query.trim()} onClick={() => run(async () => { const r = await request<{ addedEvidenceCount: number; duplicateCount: number; errors: string[] }>(`topics/${data.topic.id}/refresh`, { source: "search", query }); await onUpdated(); if (r.errors.length) throw new Error(r.errors.join("；")); notify(`新收集 ${r.addedEvidenceCount} 份来源，跳过 ${r.duplicateCount} 份重复内容。`); })}><RefreshCw size={15} /> 更新搜索来源</BusyButton></div><span className="field-hint">{user.mode === "replay" ? "当前身份使用演示回放，不会读取真实知乎数据。" : "按官方 API 返回范围获取摘要，并保留来源与时间。"}</span></div>}
    <ErrorNotice message={error} />{focusIds?.length ? <label className="check-field"><input type="checkbox" checked={onlyFocused} onChange={e => setOnlyFocused(e.target.checked)} /><span>只看这个条件的依据</span></label> : null}
    <div className="source-list">{data.evidence.filter(e => !onlyFocused || focusIds?.includes(e.id)).map((e, index) => <article className="source-card" key={e.id}><div className="source-top"><span className="source-number">{String(index + 1).padStart(2, "0")}</span><div><strong>{e.title || "一份亲身经历"}</strong><small>{e.displayAuthor} · {dateLabel(e.fetchedAt)}</small></div><span className={`mode-tag ${e.provenance.mode}`}>{e.sourceVerification === "user_provided_unverified" ? "贡献者提供 · 待核对" : e.provenance.mode === "replay" ? "示例" : e.sourceType === "experience" ? "用户贡献" : "知乎来源"}</span></div><p>{e.summary}</p><div className="source-bottom">{e.url ? <a href={e.url} target="_blank" rel="noreferrer">打开原始来源 <ExternalLink size={14} /></a> : <span>{e.provenance.mode === "replay" ? "教学示例，无知乎原文链接" : "站内贡献"}</span>}{user?.role === "maintainer" && e.visibility === "public" && <label><input type="checkbox" checked={selected.includes(e.id)} onChange={event => setSelected(prev => event.target.checked ? [...prev, e.id] : prev.filter(id => id !== e.id))} />用于修订</label>}</div>{user && onReport && <button className="text-button report-link" onClick={() => onReport(e.id)}><Flag size={13} /> 反馈这份来源的问题</button>}</article>)}</div>
    {onContributeSource && <button className="secondary-button" onClick={onContributeSource}><Link2 size={16} /> 我有一份相关来源</button>}
    {user?.role === "maintainer" && <div className="dialog-actions"><BusyButton busy={busy} disabled={!selected.length} onClick={() => run(async () => { await request(`topics/${data.topic.id}/revisions`, { evidenceIds: selected }); await onUpdated(); setSelected([]); notify("看山提出了一份修订，请到答案成长记中审阅。"); }, "updating")}><Sparkles size={17} /> 根据选中的 {selected.length} 份证据提出修订</BusyButton></div>}
  </div>;
}

export function PreferencesFlow({ session, theme, setTheme, onLoggedOut }: { session: Session | null; theme: Theme; setTheme: (theme: Theme) => void; onLoggedOut: () => Promise<void> }) {
  const { busy, run, error } = useOperation();
  return <div><h3 className="panel-section-title">选一本喜欢的小本子</h3><div className="theme-picker">{themes.map(item => <button className={`theme-swatch swatch-${item.id}`} key={item.id} aria-pressed={theme === item.id} onClick={() => setTheme(item.id)}><span className="swatch-art"><span /><span /><Kanshan pose={item.id === "notebook" ? "working" : item.id === "glacier" ? "idle" : "wave"} alt="" /></span><strong>{item.label}</strong><small>{item.description}</small>{theme === item.id && <CheckCircle2 className="theme-check" size={20} />}</button>)}</div><h3 className="panel-section-title">当前身份</h3><div className="account-card"><Avatar name={session?.user?.displayName ?? "游客"} url={session?.user?.avatarUrl} /><div><strong>{session?.user?.displayName ?? "访客"}</strong><p>{session?.user ? `${session.user.role === "maintainer" ? "维护者" : "经验贡献者"} · ${session.user.mode === "replay" ? "独立体验空间" : "知乎授权身份"}` : "可以先浏览，再决定要不要加入"}</p></div></div>
    {session?.user && <BusyButton busy={busy} className="secondary-button" onClick={() => run(async () => { await request("auth/logout", {}); await onLoggedOut(); })}>退出当前身份</BusyButton>}
    <h3 className="panel-section-title">知乎接入状态</h3><div className="connection-status"><span>知乎账号授权</span><strong>{session?.capabilities.zhihuOAuth.available ? "已配置，等待授权" : browserDemo ? "报名演示未连接真实账号" : "尚未完成配置"}</strong></div><p className="field-hint">演示空间始终使用回放，真实账号与真实数据单独保存。下一问与回复保存在本站议题讨论区。</p>{!browserDemo && <details className="connection-details"><summary>维护者接入说明</summary><p>在服务端配置官方开放平台 Access Secret、OAuth 应用与已确认的用户身份接口，再配置模型服务。密钥只放在本地环境文件或部署平台，不在网页输入。</p><a href="https://developer.zhihu.com/" target="_blank" rel="noreferrer">查看知乎开放平台 <ExternalLink size={14} /></a></details>}{browserDemo && <p className="field-hint">使用虚构教学数据与规则演示；不会发送到知乎，也不会同步到其他设备。清除网站数据会重置当前体验。</p>}<ErrorNotice message={error} />
  </div>;
}
