import { randomUUID } from "node:crypto";
import { sql } from "drizzle-orm";
import { pgTable, text, timestamp, integer, doublePrecision, jsonb, uniqueIndex, index, foreignKey, check } from "drizzle-orm/pg-core";
import type { AnyPgColumn, PgTableExtraConfigValue, ForeignKeyBuilder } from "drizzle-orm/pg-core";
import type { ConditionSnapshot, ContributionKind, ModelRun, Provenance, VersionDiff } from "../domain/index";
const id = () => text("id").primaryKey().$defaultFn(randomUUID);
const time = (name: string) => timestamp(name, { withTimezone:true, mode:"string" });
const created = () => time("created_at").notNull().defaultNow();
const workspace = () => text("workspace_id").notNull().references(() => workspaces.id);
const jsonStrings = (name:string) => jsonb(name).$type<string[]>().notNull().default([]);
export const workspaces = pgTable("workspaces", { id:id(), kind:text("kind").$type<"preview"|"live"|"demo">().notNull(), createdAt:created() }, t => [check("workspace_kind",sql`${t.kind} in ('preview','live','demo')`)]);
export const users = pgTable("users", {
 id:id(), workspaceId:workspace(), providerMode:text("provider_mode").$type<"live"|"replay">().notNull(), providerSubject:text("provider_subject"), displayName:text("display_name").notNull(), avatarUrl:text("avatar_url"), role:text("role").$type<"contributor"|"maintainer">().notNull().default("contributor"), encryptedAccessToken:text("encrypted_access_token"), encryptedRefreshToken:text("encrypted_refresh_token"), tokenExpiresAt:time("token_expires_at"), createdAt:created(),
}, t => [uniqueIndex("users_workspace_id").on(t.workspaceId,t.id),uniqueIndex("users_provider_subject").on(t.workspaceId,t.providerMode,t.providerSubject),check("user_role",sql`${t.role} in ('contributor','maintainer')`),check("user_mode",sql`${t.providerMode} in ('live','replay')`)]);
export const sessions = pgTable("sessions", { idHash:text("id_hash").primaryKey(), userId:text("user_id").notNull(), workspaceId:workspace(), expiresAt:time("expires_at").notNull(), createdAt:created(), revokedAt:time("revoked_at") },t=>[foreignKey({columns:[t.workspaceId,t.userId],foreignColumns:[users.workspaceId,users.id]}),index("sessions_expiry").on(t.expiresAt)]);
export const oauthStates = pgTable("oauth_states", { idHash:text("id_hash").primaryKey(),browserBindingHash:text("browser_binding_hash").notNull(),returnTo:text("return_to").notNull(),codeVerifierEncrypted:text("code_verifier_encrypted"),expiresAt:time("expires_at").notNull(),consumedAt:time("consumed_at"),createdAt:created() });
export const topics = pgTable("topics", {
 id:id(),workspaceId:workspace(),slug:text("slug").notNull(),title:text("title").notNull(),template:text("template").$type<"learning"|"social">().notNull(),summary:text("summary").notNull(),currentVersionId:text("current_version_id").references(():AnyPgColumn=>claimVersions.id),creatorId:text("creator_id").references(()=>users.id),circleId:text("circle_id"),status:text("status").notNull().default("active"),createdAt:created(),updatedAt:time("updated_at").notNull().defaultNow(),
},(t):PgTableExtraConfigValue[]=>[uniqueIndex("topics_workspace_id").on(t.workspaceId,t.id),uniqueIndex("topics_workspace_slug").on(t.workspaceId,t.slug),foreignKey({columns:[t.workspaceId,t.id,t.currentVersionId],foreignColumns:[claimVersions.workspaceId,claimVersions.topicId,claimVersions.id]}),check("topic_template",sql`${t.template} in ('learning','social')`)]);
const topicFk = (t:{workspaceId:AnyPgColumn;topicId:AnyPgColumn}):ForeignKeyBuilder => foreignKey({columns:[t.workspaceId,t.topicId],foreignColumns:[topics.workspaceId,topics.id]});
export const consents = pgTable("consents",{ id:id(),workspaceId:workspace(),userId:text("user_id").notNull(),purpose:text("purpose").notNull(),displayMode:text("display_mode").notNull(),payloadHash:text("payload_hash").notNull(),preview:text("preview"),expiresAt:time("expires_at"),confirmedAt:time("confirmed_at"),revokedAt:time("revoked_at"),createdAt:created() },t=>[uniqueIndex("consents_workspace_id").on(t.workspaceId,t.id),foreignKey({columns:[t.workspaceId,t.userId],foreignColumns:[users.workspaceId,users.id]})]);
export const experiences = pgTable("experiences",{
 contributionKind:text("contribution_kind").$type<ContributionKind>().notNull().default("experience"),replyToProbeId:text("reply_to_probe_id"),sourceUrl:text("source_url"),displayAvatarUrl:text("display_avatar_url"),
 id:id(),workspaceId:workspace(),topicId:text("topic_id").notNull(),ownerId:text("owner_id").notNull(),rawText:text("raw_text"),publicText:text("public_text").notNull(),displayMode:text("display_mode").$type<"nickname"|"anonymous"|"pseudonym">().notNull(),displayName:text("display_name").notNull(),consentId:text("consent_id").notNull(),analysisStatus:text("analysis_status").$type<"pending"|"processing"|"ready"|"needs_review"|"failed">().notNull().default("pending"),analysisError:text("analysis_error"),extractedConditions:jsonStrings("extracted_conditions"),caveats:jsonStrings("caveats"),createdAt:created(),withdrawnAt:time("withdrawn_at"),deletedAt:time("deleted_at"),
},(t):PgTableExtraConfigValue[]=>[uniqueIndex("experiences_workspace_id").on(t.workspaceId,t.id),topicFk(t),foreignKey({columns:[t.workspaceId,t.topicId,t.replyToProbeId],foreignColumns:[probes.workspaceId,probes.topicId,probes.id]}),foreignKey({columns:[t.workspaceId,t.ownerId],foreignColumns:[users.workspaceId,users.id]}),foreignKey({columns:[t.workspaceId,t.consentId],foreignColumns:[consents.workspaceId,consents.id]}),check("experience_display_mode",sql`${t.displayMode} in ('nickname','anonymous','pseudonym')`),check("contribution_kind",sql`${t.contributionKind} in ('experience','comment','evidence')`),check("evidence_source_required",sql`${t.contributionKind} <> 'evidence' or ${t.sourceUrl} is not null or ${t.withdrawnAt} is not null or ${t.deletedAt} is not null`),check("avatar_identity_scope",sql`${t.displayMode} = 'nickname' or ${t.displayAvatarUrl} is null`)]);
export const evidence = pgTable("evidence",{
 id:id(),workspaceId:workspace(),topicId:text("topic_id").notNull(),sourceType:text("source_type").$type<"search"|"circle"|"experience"|"replay">().notNull(),provider:text("provider").notNull(),sourceId:text("source_id").notNull(),url:text("url"),title:text("title"),summary:text("summary").notNull(),displayAuthor:text("display_author").notNull(),fetchedAt:time("fetched_at").notNull(),contentHash:text("content_hash").notNull(),visibility:text("visibility").$type<"public"|"quarantined"|"unavailable">().notNull().default("public"),provenance:jsonb("provenance").$type<Provenance>().notNull(),experienceId:text("experience_id"),createdAt:created(),
},t=>[uniqueIndex("evidence_workspace_id").on(t.workspaceId,t.id),uniqueIndex("evidence_source_content").on(t.workspaceId,t.topicId,t.provider,t.sourceId,t.contentHash),topicFk(t),foreignKey({columns:[t.workspaceId,t.experienceId],foreignColumns:[experiences.workspaceId,experiences.id]})]);
export const conditions = pgTable("conditions",{ id:id(),workspaceId:workspace(),topicId:text("topic_id").notNull(),label:text("label").notNull(),description:text("description").notNull(),kind:text("kind").$type<"support"|"conflict"|"unknown"|"context">().notNull(),evidenceIds:jsonStrings("evidence_ids"),status:text("status").notNull().default("active") },t=>[uniqueIndex("conditions_workspace_id").on(t.workspaceId,t.id),uniqueIndex("conditions_topic_id").on(t.workspaceId,t.topicId,t.id),topicFk(t),check("condition_kind",sql`${t.kind} in ('support','conflict','unknown','context')`)]);
export const claimVersions = pgTable("claim_versions",{
 id:id(),workspaceId:workspace(),topicId:text("topic_id").notNull(),versionNumber:integer("version_number").notNull(),baseVersionId:text("base_version_id").references(():AnyPgColumn=>claimVersions.id),text:text("text").notNull(),conditionsSnapshot:jsonb("conditions_snapshot").$type<ConditionSnapshot[]>().notNull().default([]),evidenceIds:jsonStrings("evidence_ids"),contributorDisplaySnapshot:jsonStrings("contributor_display_snapshot"),reviewerId:text("reviewer_id").references(()=>users.id),createdAt:created(),publishedAt:time("published_at"),status:text("status").$type<"draft"|"published"|"superseded">().notNull(),
},(t):PgTableExtraConfigValue[]=>[uniqueIndex("versions_workspace_id").on(t.workspaceId,t.id),uniqueIndex("versions_topic_id").on(t.workspaceId,t.topicId,t.id),uniqueIndex("versions_topic_number").on(t.workspaceId,t.topicId,t.versionNumber),uniqueIndex("versions_one_published").on(t.workspaceId,t.topicId).where(sql`${t.status} = 'published'`),topicFk(t),check("version_number_positive",sql`${t.versionNumber}>0`)]);
export const matches = pgTable("matches",{ id:id(),workspaceId:workspace(),experienceId:text("experience_id").notNull(),conditionIds:jsonStrings("condition_ids"),evidenceIds:jsonStrings("evidence_ids"),relation:text("relation").$type<"support"|"conflict"|"extends"|"unknown">().notNull(),reasons:jsonStrings("reasons"),confidence:doublePrecision("confidence").notNull(),modelRun:jsonb("model_run").$type<ModelRun>().notNull(),createdAt:created() },t=>[foreignKey({columns:[t.workspaceId,t.experienceId],foreignColumns:[experiences.workspaceId,experiences.id]}),check("match_two_reasons",sql`jsonb_array_length(${t.reasons})>=2`),check("match_confidence",sql`${t.confidence}>=0 and ${t.confidence}<=1`)]);
export const probes = pgTable("probes",{
 id:id(),workspaceId:workspace(),topicId:text("topic_id").notNull(),question:text("question").notNull(),targetUnknownId:text("target_unknown_id").notNull(),rationale:text("rationale").notNull(),evidenceIds:jsonStrings("evidence_ids"),informationGainExplanation:text("information_gain_explanation").notNull(),status:text("status").$type<"draft"|"needs_review"|"approved"|"asked"|"answered"|"rejected"|"deferred"|"expired">().notNull().default("draft"),baseVersionId:text("base_version_id").notNull(),modelRun:jsonb("model_run").$type<ModelRun>().notNull(),reviewerId:text("reviewer_id").references(()=>users.id),approvedAt:time("approved_at"),createdAt:created(),decisionReason:text("decision_reason"),
},t=>[uniqueIndex("probes_workspace_id").on(t.workspaceId,t.id),uniqueIndex("probes_topic_id").on(t.workspaceId,t.topicId,t.id),topicFk(t),foreignKey({columns:[t.workspaceId,t.topicId,t.targetUnknownId],foreignColumns:[conditions.workspaceId,conditions.topicId,conditions.id]}),foreignKey({columns:[t.workspaceId,t.topicId,t.baseVersionId],foreignColumns:[claimVersions.workspaceId,claimVersions.topicId,claimVersions.id]})]);
export const revisions = pgTable("revision_proposals",{
 id:id(),workspaceId:workspace(),topicId:text("topic_id").notNull(),baseVersionId:text("base_version_id").notNull(),proposedText:text("proposed_text").notNull(),proposedConditions:jsonb("proposed_conditions").$type<ConditionSnapshot[]>().notNull(),diff:jsonb("diff").$type<VersionDiff[]>().notNull(),evidenceIds:jsonStrings("evidence_ids"),contributorIds:jsonStrings("contributor_ids"),explanation:text("explanation").notNull(),confidence:doublePrecision("confidence").notNull(),status:text("status").$type<"proposed"|"needs_review"|"accepted"|"rejected"|"deferred">().notNull().default("proposed"),modelRun:jsonb("model_run").$type<ModelRun>().notNull(),reviewerId:text("reviewer_id").references(()=>users.id),decidedAt:time("decided_at"),createdAt:created(),decisionReason:text("decision_reason"),acceptedVersionId:text("accepted_version_id").references(()=>claimVersions.id),
},t=>[uniqueIndex("revisions_workspace_id").on(t.workspaceId,t.id),topicFk(t),foreignKey({columns:[t.workspaceId,t.topicId,t.baseVersionId],foreignColumns:[claimVersions.workspaceId,claimVersions.topicId,claimVersions.id]}),check("revision_confidence",sql`${t.confidence}>=0 and ${t.confidence}<=1`)]);
export interface PublicationPayload { text:string; target:"in_app"|"zhihu_circle"; displayIdentity:string; sourceUrls:string[]; baseVersionId:string; circleId?:string; [key:string]:unknown }
export const publications = pgTable("publications",{
 id:id(),workspaceId:workspace(),topicId:text("topic_id").notNull(),probeId:text("probe_id").notNull(),approvalId:text("approval_id").notNull(),approvedById:text("approved_by_id").notNull().references(()=>users.id),providerMode:text("provider_mode").$type<"live"|"replay">().notNull(),targetCircleId:text("target_circle_id"),immutablePayload:jsonb("immutable_payload").$type<PublicationPayload>().notNull(),previewHash:text("preview_hash").notNull(),idempotencyKey:text("idempotency_key").notNull(),status:text("status").$type<"pending"|"sending"|"sent"|"retryable_failed"|"permanently_failed"|"needs_reconciliation">().notNull().default("pending"),attemptCount:integer("attempt_count").notNull().default(0),nextAttemptAt:time("next_attempt_at"),leaseOwner:text("lease_owner"),leaseUntil:time("lease_until"),remoteId:text("remote_id"),remoteUrl:text("remote_url"),lastError:text("last_error"),createdAt:created(),sentAt:time("sent_at"),
},t=>[topicFk(t),foreignKey({columns:[t.workspaceId,t.probeId],foreignColumns:[probes.workspaceId,probes.id]}),uniqueIndex("publication_approval").on(t.workspaceId,t.approvalId),uniqueIndex("publication_idempotency").on(t.workspaceId,t.idempotencyKey),index("publication_worker_queue").on(t.status,t.nextAttemptAt)]);
export const auditEvents = pgTable("audit_events",{ id:id(),workspaceId:workspace(),topicId:text("topic_id"),actorId:text("actor_id").references(()=>users.id),actorMode:text("actor_mode").$type<"live"|"replay"|"system">().notNull(),type:text("type").notNull(),entityType:text("entity_type").notNull(),entityId:text("entity_id").notNull(),payloadSummary:jsonb("payload_summary").$type<Record<string,string|number|boolean|null>>().notNull().default({}),occurredAt:time("occurred_at").notNull().defaultNow() },t=>[topicFk(t),index("audit_workspace_topic_time").on(t.workspaceId,t.topicId,t.occurredAt)]);
export const reports = pgTable("reports",{ id:id(),workspaceId:workspace(),topicId:text("topic_id").notNull(),entityType:text("entity_type").notNull(),entityId:text("entity_id").notNull(),reporterId:text("reporter_id").notNull().references(()=>users.id),reason:text("reason").notNull(),status:text("status").$type<"pending"|"dismissed"|"hidden">().notNull().default("pending"),createdAt:created(),reviewerId:text("reviewer_id").references(()=>users.id),resolvedAt:time("resolved_at"),decisionReason:text("decision_reason") },t=>[topicFk(t)]);
export const idempotencyRecords = pgTable("idempotency_records",{ id:id(),workspaceId:workspace(),actorId:text("actor_id").notNull(),route:text("route").notNull(),key:text("key").notNull(),payloadHash:text("payload_hash").notNull(),response:jsonb("response").$type<unknown>().notNull(),createdAt:created() },t=>[foreignKey({columns:[t.workspaceId,t.actorId],foreignColumns:[users.workspaceId,users.id]}),uniqueIndex("idempotency_actor_route_key").on(t.workspaceId,t.actorId,t.route,t.key)]);
export const sourceSnapshots = pgTable("source_snapshots",{ id:id(),workspaceId:workspace(),topicId:text("topic_id").notNull(),provider:text("provider").notNull(),mode:text("mode").$type<"live"|"replay">().notNull(),payload:jsonb("payload").$type<Record<string,unknown>>().notNull(),fetchedAt:time("fetched_at").notNull(),lastError:text("last_error"),createdAt:created() },t=>[topicFk(t),index("source_snapshots_latest").on(t.workspaceId,t.topicId,t.provider,t.fetchedAt)]);
